import React from 'react';

const Privacy = () => {
  return (
    <div className="bg-gray-50">
      <main className="flex flex-col items-center justify-center min-h-screen py-2">
        <div className="w-full px-4 pt-8 ">
         
            <h1 className="text-3xl font-bold text-center mb-6">Privacy Policy</h1>
            <p className="text-center text-gray-600 mb-8">Updated at 2024-07-04</p>

            <div className="prose max-w-none">
              <p className="mb-4">
                Importmoz ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Importmoz.
              </p>

              <h2 className="text-2xl font-bold mt-8 mb-4">Definitions and key terms</h2>
              <p className="mb-4">
                To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:
              </p>
              <ul className="list-disc pl-8 mb-8">
                <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
                <li><strong>Company:</strong> when this policy mentions "Company," "we," "us," or "our," it refers to Importmoz, Mozambique that is responsible for your information under this Privacy Policy.</li>
                <li><strong>Country:</strong> where Importmoz or the owners/founders of Importmoz are based, in this case is Mozambique</li>
                <li><strong>Customer:</strong> refers to the company, organization or person that signs up to use the Importmoz Service to manage the relationships with your consumers or service users.</li>
                <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Importmoz and use the services.</li>
                <li><strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
                <li><strong>Personnel:</strong> refers to those individuals who are employed by Importmoz or are under contract to perform a service on behalf of one of the parties.</li>
                <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
                <li><strong>Service:</strong> refers to the service provided by Importmoz as described in the relative terms (if available) and on this platform.</li>
                <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
                <li><strong>Website:</strong> Importmoz's site, which can be accessed via this URL: https://importmoz.com</li>
                <li><strong>You:</strong> a person or entity that is registered with Importmoz to use the Services.</li>
              </ul>

              <h2 className="text-2xl font-bold mt-8 mb-4">What Information Do We Collect?</h2>
              <p className="mb-4">
                We collect information from you when you visit our website/app, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.
              </p>
              <ul className="list-disc pl-8 mb-8">
                <li>Name / Username</li>
                <li>Phone Numbers</li>
                <li>Email Addresses</li>
              </ul>

              <h2 className="text-2xl font-bold mt-8 mb-4">How Do We Use The Information We Collect?</h2>
              <p className="mb-4">
                Any of the information we collect from you may be used in one of the following ways:
              </p>
              <ul className="list-disc pl-8 mb-8">
                <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
                <li>To improve our website/app (we continually strive to improve our website/app offerings based on the information and feedback we receive from you)</li>
                <li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</li>
                <li>To process transactions</li>
                <li>To administer a contest, promotion, survey or other site feature</li>
                <li>To send periodic emails</li>
              </ul>

              {/* Continue with the rest of the privacy policy content */}
              {/* ... */}

              <h2 className="text-2xl font-bold mt-8 mb-4">Contact Us</h2>
              <p className="mb-4">
                Don't hesitate to contact us if you have any questions.
              </p>
              <ul className="list-disc pl-8 mb-8">
                <li>Via Email: info@importmoz.com</li>
                <li>Via Phone Number: 824463475</li>
                <li>Via this Link: https://importmoz.com</li>
              </ul>
            </div>
        
        </div>
      </main>
    </div>
  );
};

export default Privacy;
